---
title: Ideas for the workshop
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---
***

#### 1. Brief Introduction for Meetup

Este workshop é para todas e todos os que querem aprender R ou actualizar alguns conceitos básicos de R e partilhar conhecimento também! Será possível começar logo a programar em R e a produzir alguns exemplos úteis de visualização de dados. Este é o primeiro passo para te motivar a aprender mais sobre dados e a contar boas histórias com os mesmos.

***

This workshop is for who wants to learn R or refresh some basic concepts in R and share some knowledge too! You'll be able to start right away with the R language and produce some useful data visualizations. This is a first step to motivate you to understand more about data and tell good stories with it.


#### 2. Useful links

* https://www.thinkwithgoogle.com/articles/tell-meaningful-stories-with-data.html
* http://www.thinkwithgoogle.com/articles/data-stories.html
* https://www.thinkwithgoogle.com/articles/data-to-insights-blueprint-for-your-business.html


#### **3. Instructions pre-workshop**

<span style = "color: green"> Add instructions to download R and install R studio</span>


#### **4. Workshop content**

4.1. Objectives

This workshop aims at introducing the R language to non-users by enabling them to make simple data visualizations. People who had previously contacted with R will also benefit from this workshop by refreshing previous concepts and sharing ideas and critical thinking with others. 

At the end of the workshop participants should:
* Understand what is R and it's usage 
* Be able to use specific code and change some of it's arguments to customize the output
* Use a specific dataset, select specific variables and produce a data visualization 

<span style = "color: green">Add PT version</span>


4.2. Scope
A brief introduction to R and to some data visualization associated packages and functions will be given. However, R grammar and syntax will not be covered in detail for this workshop.
Data analysis and data analysis interpretation will be out of the scope for this workshop. This can be covered in a future workshop


4.3. Plano/Programa 


**Para nós**

9h15 - Recepção dos participantes/Welcome

9h30 - Introdução da comunidade R-Ladies Lisboa

9h45 - Sorteio de grupos

10h -  Introdução à visualização de dados

10h05 - Apresentação da base de dados exemplo (de preferencia algo que dê para storytelling)

10h10 - Exercício 1 (desenhar visualização de dados em papel)

10h15 - Iniciar R-Studio - explicação genérica sobre o programa (janelas, output, ajuda, gravar ficheiro)

10h25 - Dicas para Exercício 1 - mostrar código plot e ggplot2

10h30 - Prática - Reprodução do mesmo código - Para quem conseguir fazer, sugestão de alteração de alguns argumentos

11h15 - 11h30 - Cafézinho e Comida! 

11h40 - Exercício 2 - mostrar outro exemplo de código e introduzir 3 exemplos de bases de dados

11h45- Grupos devem escolher 1 tema e produzir 1 visualização

12h - Apresentação de cada grupo (1-2 mins cada)

12h15 - Finalização do workshop e anunciar eventos futuros


**Para os participantes**

9h15 - Recepção - Boas vindas

9h30 - Introdução da comunidade R-Ladies Lisboa

9h45 - Sorteio e formação de grupos

10h -  Introdução à visualização de dados

10h05 - Apresentação de um exemplo de base de dados 

10h15 - Iniciar R-Studio - Breve explicação

10h30 - Exercício 1

11h15 - 11h30 - Cafézinho e Comida! 

11h40 - Exercício 2 

12h00 - Apresentação de cada grupo (1-2 mins cada)

12h30 - Finalização do workshop e anunciar eventos futuros


**Para o meetup**

9h15 - Recepção - Boas vindas

9h30 - Introdução da comunidade R-Ladies Lisboa

10h -  Introdução à visualização de dados

10h30 - Exercícios

11h15 - 11h30 - Cafézinho e Comida! 

11h40 - Exercícios

12h30 - Finalização do workshop 


<span style = "color: green"> **Add english version** </span>


3.4. Content

* Brief intro to R (founders maybe), R syntax (some brief examples to try - see on R Ladies RTP data vis workhop - info on github), base plot and ggplot2
* Data visualization is not data analysis but can be a useful tool for story telling

