# Instalação de R e R-Studio ***(Installing R and R-Studio)***

Para participar activamente no segundo workshop do R-Ladies (‘Visualização de Dados’), deve trazer consigo um computador portátil. Para que o computador execute código em R é necessário: 

 - instalar R
 
 - instalar R-Studio.
 
As instruções que se seguem explicam como fazer estas duas instalações em computadores com sistema operativo Mac ou Windows.

***To actively participate in the second workshop of R-Ladies (‘Data Visualization’) you must bring a laptop. To be able to execute R code in the laptop you have to:***

 ***- install R*** 
 
 ***- install R-Studio***
 
***The following instructions explain how to perform these 2 installations in computers with Mac and Windows operating systems.***

## Instalar R e R-Studio num Mac ***(Install R and R-Studio for Mac)***

Os links seguintes contêm vídeos que explicam como instalar R e R-studio num Mac:

https://www.youtube.com/watch?v=uxuuWXU-7UQ (R)

https://www.youtube.com/watch?v=JbTMvQ-SbvQ (R-Studio)

Em alternativa, pode simplesmente guiar-se pelas seguintes instruções.

***The following links contain videos guiding you to install R and R-Studio for Mac:***

***https://www.youtube.com/watch?v=uxuuWXU-7UQ (R)***

***https://www.youtube.com/watch?v=JbTMvQ-SbvQ (R-Studio)***

***In alternative to the videos, you can simply follow the instructions below.***

### Instalar R ***(Install R)***
Abra o browser da web e vá à página do CRAN (Comprehensive R Archive Network):

https://cran.r-project.org/

Verá que há várias alternativas de download para diferentes plataformas. Clique em "Download R for (Mac) OS X". Em seguida clique em "R-3.3.2.pkg" e espere que o download esteja completo.

Quando o download terminar, abra o documento descarregado. Isto iniciará o instalador. Siga simplesmente as instruções do instalador e aceite as definições pré-estabelecidas.

***Open your web browser and go to CRAN (Comprehensive R Archive Network):***

***https://cran.r-project.org/***

***You'll see that there are a number of options of download for different platforms. Click on "Download R for (Mac) OS X". Then click on "R-3.3.2.pkg" and wait for the download to complete.***
 
***Once it's finished downloading, open up the package. This will start the installer. Just follow the instructions of the installer and accept the default settings.***

### Instalar R-Studio ***(Install R-Studio)***
É importante notar que só é possível instalar o R-Studio no seu computador se já tiver préviamente instalado o R. Depois de instalar R, abra o browser da web e vá à página do R-Studio:

https://www.rstudio.com/products/rstudio/download/

Deslize para o fim da página onde diz **"Installers for Supported Platforms"** e clique em **"RStudio 1.0.136 - Mac OS X 10.6+ (64-bit)"**. 

Quando o download estiver completo, vá à pasta ‘Downloads’ e clique 2-vezes no ficheiro descarregado. Isto deverá iniciar o instalador. Basta seguir as instruções do instalador e aceitas as definições pré-estabelecidas.

Como em qualquer aplicação para Mac, é necessário colocar o shortcut do R-Studio na pasta ‘Aplicações’. Para iniciar R-Studio só precisa de ir à pasta ‘Aplicações’ e clicar 2-vezes em R-Studio.

***It is important to note that you need to have R already installed in your computer to be able to install R-Studio. Once you have installed R, open your web browser and go to the website of R-Studio:***

***https://www.rstudio.com/products/rstudio/download/***

***Scroll down to the end of the page where it says "Installers for Supported Platforms" and click "RStudio 1.0.136 - Mac OS X 10.6+ (64-bit)".*** 

***Once the download is complete, go to the ‘Downloads’ folder and click on the downloaded file. This should start the installer. Simply follow the instructions and accept the default parameters.***

***Just like any other Mac application, you need to drag the R-Studio shortcut into the ‘Applications’ folder.***

***To start R-Studio, just go to the applications folder and double on R-Studio.***


## Instalar R e R-Studio num Windows ***(Install R and R-Studio for Windows)***

O link seguinte contém um video que explica como instalar R e R-studio em Windows:

https://www.youtube.com/watch?v=5ZbjUEg4a1g

Em alternativa, pode simplesmente guiar-se pelas seguintes instruções.

***A video to guide you in the installation of R and R-Studio for Windows can be found here:***

***https://www.youtube.com/watch?v=5ZbjUEg4a1g***

***In alternative to the video, you can simply follow the instructions below.***


### Instalar R ***(Install R)***
Abra o browser da web e vá à página do CRAN (Comprehensive R Archive Network):

https://cran.r-project.org/

Verá que há várias alternativas de download para diferentes plataformas. Será direccionado para uma nova página, onde deverá clicar em ‘base’. Na página seguinte, clique em ‘Download R 3.3.2 for Windows’.

Quando o download terminar, abra o documento descarregado. Isto iniciará o instalador. Siga simplesmente as instruções do instalador e aceite as definições pré-estabelecidas.

***Open your web browser and go to CRAN (Comprehensive R Archive Network):***

***https://cran.r-project.org/***

***You'll see that there are a number of options for you to download here for different platforms. Click on the option for Windows.*** 

 ***You’ll be directed to the following window, where you have to click on ‘base’. On the next page click on ‘Download R 3.3.2 for Windows’.*** 

***Once it's finished downloading, open up the package. This will start the installer. Just follow the instructions of the installer and accept the default parameters.***


### Instalar R-Studio ***(Install R-Studio)***

É importante notar que só é possível instalar o R-Studio no seu computador se já tiver préviamente instalado o R. Depois de instalar R, abra o browser da web e vá à página do R-Studio:

https://www.rstudio.com/products/rstudio/download/

Deslize para o fim da pagina onde diz "Installers for Supported Platforms" e clique em "RStudio 1.0.136 - Windows Vista/7/8/10". 

Quando o download estiver completo, vá à pasta ‘Downloads’ e clique 2-vezes no ficheiro descarregado. Isto deverá iniciar o instalador. Basta seguir as instruções do instalador e aceitar as definições pré-estabelecidas.

***It is important to note that you need to have R already installed in your computer to be able to install R-Studio. Open your web browser and go to the website of R-Studio:***

***https://www.rstudio.com/***

***Scroll down to the end of the page where it says "Installers for Supported Platforms" and click "RStudio 1.0.136 - Windows Vista/7/8/10".*** 

***Once the download is complete, open the downloaded file. This should start the installation. Simply follow the instructions in the installer and accept the default parameters.***
